language: android
jdk: oraclejdk8
branches:
  only:
    - master
before_script:
  # Download desired version of Gradle
  - wget http://services.gradle.org/distributions/gradle-6.7.1-bin.zip
  - unzip -qq gradle-6.7.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.7.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  # just to test gradle version, against our provided one
  - gradle -v
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a -c 512M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-29
    - android-19
    - sys-img-armeabi-v7a-android-19